### ISSUE TITLE
Tags are not respected?

### ISSUE THREAD

**Issue by YuriGal** [ekristen/aws-nuke#110]
We tag our resources that we want to keep from nuking with key `do-not-nuke` and value `true`, then we add this to filter section - and for majority of resources it works. But for some resources it's ignored. For example we tagged a Sagemaker domain: 

![Screenshot 2024-03-07 at 4 29 54 PM](https://github.com/ekristen/aws-nuke/assets/50464505/7b9f24d1-560f-4ee7-a7b8-55f61b5200b9)

And using filter similar to this one:

```
accounts:
  '123456789':
    filters:
      SageMakerDomain:
      - property: "tag:do-not-nuke"
        value: "true"
```

Similar setup works for majority of other resources, yet here we're getting output

```
us-west-2 - SageMakerDomain - d-lkdfjldfadsf - [DomainID: "d-lkdfjldfadsf"] - would remove
```

is it a bug, or some omission on our side? How do we make it respect the tags?

**Comment by ekristen** [comment]
@YuriGal it looks like SageMakerDomain doesn't have tag support, should be trivial for me to add, I'll take a look tonight.

**Comment by YuriGal** [comment]
That would be awesome! Would it be possible to add this to other similar resources? I know some resources can't be tagged at all in AWS, but if all of those that can could be filtered by tags it would be great.

**Comment by ekristen** [comment]
Yes, as long as the resource supports tags, the resource in this project just needs to be identified as needing it's tags exposed and then filtering will work.

**Comment by YuriGal** [comment]
Not sure if I am doing something wrong, but with `v3.0.0-beta.32` SageMakerDomain is always excluded, no matter tagged or not.

**Comment by ekristen** [comment]
What happens exactly? Does it show up as "filtered by config"? Can you please provide the output and the config?

**Comment by ekristen** [comment]
@YuriGal let me know when you get a chance. I'll see what I can do to replicate or test.

**Comment by YuriGal** [comment]
Ok, so to simplify testing I am using a basic config like this
```
regions:
  - global
  - us-west-2
  - us-east-1
  - eu-central-1
  - af-south-1
account-blocklist:
  - "123456789"
accounts:
  '987654321':
    filters:
      SageMakerDomain:
      - property: "tag:role:do-not-nuke"
        value: "true"
resource-types:
  targets:
    - SageMakerDomain
```
There is a sagemaker domain in `us-west-2`, but no matter whether it's tagged or not I am getting
```
Scan complete: 0 total, 0 nukeable, 0 filtered.
```
