### ISSUE TITLE
Filter properties are not respected

### ISSUE THREAD

**Issue by YuriGal** [ekristen/aws-nuke#115]
Part of my filter is set like this
```
      EC2InternetGatewayAttachment:
      - property: "vpc:OwnerID"
        value: "123456789"
      EC2RouteTable:
      - property: "OwnerID"
        value: "123456789"
      EC2DHCPOption:
      - property: "OwnerID"
        type: "regex"
        value: "(123456789|987654321)"
```
The account has resources with Owner ID that match the filter. The original nuke had those filtered out. The fork still goes
```

us-west-2 - EC2InternetGatewayAttachment - igw-03be1339519e46fa9 -> vpc-0debf6fec89321668 - [DefaultVPC: "false"] - would remove
us-west-2 - EC2DHCPOption - dopt-0c578847d991d4df5 - [DefaultVPC: "false"] - would remove
us-west-2 - EC2RouteTable - rtb-0d7b4aa83ad8d4a37 - [DefaultVPC: "false", vpcID: "vpc-0debf6fec89321668"] - would remove
```
Would it be possible to have those filtered out? Not sure if there're other resources with the same issue, but these 3 definetely have it.
