### ISSUE TITLE
Nil pointer when listing SecretsManagerSecret resources

### ISSUE THREAD

**Issue by iuliancristea** [ekristen/aws-nuke#207]
Version: 3.2.2

### Minimal Config

```yaml
regions:
  - global
  - eu-central-1
presets:
  common:
    filters:
      global:
        - property: "tag:to-delete/.*"
          type: "regex"
          value: "true"
          invert: "true"
accounts:
  <account_id>:
    presets:
      - common
resource-types:
  includes:
    - SecretsManagerSecret
```

Hi,

When trying to delete `SecretsManagerSecret` resources, the listing operation fails with a `nil pointer` exception:

```shell
ERRO[0119]scanner.go:110 Listing SecretsManagerSecret failed:
    runtime error: invalid memory address or nil pointer dereference

    goroutine 3342 [running]:
    runtime/debug.Stack()
    	runtime/debug/stack.go:24 +0x64
    github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list.func1()
    	github.com/ekristen/libnuke@v0.17.1/pkg/scanner/scanner.go:108 +0x5c
    panic({0x109956440?, 0x10e55de10?})
    	runtime/panic.go:914 +0x218
    github.com/ekristen/aws-nuke/v3/resources.(*SecretsManagerSecretLister).List(0x109ac2780?, {0x140000ae5d0?, 0x10821a64e?}, {0x108ed42c0?, 0x1400070fbb0})
    	github.com/ekristen/aws-nuke/v3/resources/secretsmanager-secret.go:50 +0x1b8
    github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0x140007233e0, {0x10ab18678?, 0x14000716fa0?}, {0x14000035b70, 0xc}, {0x10821a64e, 0x14}, {0x108ed42c0?, 0x1400070fbb0})
    	github.com/ekristen/libnuke@v0.17.1/pkg/scanner/scanner.go:124 +0x11c
    created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1
    	github.com/ekristen/libnuke@v0.17.1/pkg/scanner/scanner.go:89 +0x44
```
