### ISSUE TITLE
InvalidARN for some Elasticache resources

### ISSUE THREAD

**Issue by iuliancristea** [ekristen/aws-nuke#208]
Version: 3.2.2

### Minimal Config

```yaml
regions:
  - global
  - eu-central-1
presets:
  common:
    filters:
      global:
        - property: "tag:to-delete/.*"
          type: "regex"
          value: "true"
          invert: "true"
accounts:
  <account_id>:
    presets:
      - common
resource-types:
  includes:
    - ElasticacheCacheCluster
    - ElasticacheSubnetGroup
```

Hi,

When running aws-nuke with the above config, the operation fails with the following errors:

```shell
ERRO[0005]elasticache-memcacheclusters.go:60 unable to retrieve tags                       error="InvalidARN: Input ARN string does not have 7 components.\n\tstatus code: 400, request id: <id>"

ERRO[0005]elasticache-subnetgroups.go:57 unable to retrieve tags                       error="InvalidARN: Input ARN string does not have 7 components.\n\tstatus code: 400, request id: <id>"
```
