### ISSUE TITLE
Inverting a filter not working as expected

### ISSUE THREAD

**Issue by eaudetcobello** [ekristen/aws-nuke#292]
The configuration:

```
accounts:
  11111111111: # AWS Account IDs are not considered sensitive information
    filters:
      __global__:
        - property: tag:sigs.k8s.io/cluster-api-provider-aws/cluster/*
          type: "glob"
          value: "owned"
          invert: true
```

Results in the following output:

```
us-east-2 - EC2VPC - vpc-0c1bef0e84fca294d - [ID: "vpc-0c1bef0e84fca294d", IsDefault: "false", OwnerID: "018302341396", tag:owner: "k8sci"] - would remove
us-east-2 - EC2VPC - vpc-0fa1d84c7067ec473 - [ID: "vpc-0fa1d84c7067ec473", IsDefault: "false", OwnerID: "018302341396", tag:Name: "capick8s-create-2ij5h1-vpc", tag:sigs.k8s.io/cluster-api-provider-aws/cluster/capick8s-create-2ij5h1: "owned", tag:sigs.k8s.io/cluster-api-provider-aws/role: "common"] - would remove
us-east-2 - EC2VPC - vpc-03f2c7351e64c6e0f - [ID: "vpc-03f2c7351e64c6e0f", IsDefault: "false", OwnerID: "018302341396", tag:owner: "k8sci"] - would remove
us-east-2 - EC2VPC - vpc-00baaeb532da792d9 - [ID: "vpc-00baaeb532da792d9", IsDefault: "true", OwnerID: "018302341396"] - would remove
us-east-2 - EC2VPC - vpc-0d9753751781ee5bb - [ID: "vpc-0d9753751781ee5bb", IsDefault: "false", OwnerID: "018302341396", tag:Name: "capick8s-create-aagvi9-vpc", tag:sigs.k8s.io/cluster-api-provider-aws/cluster/capick8s-create-aagvi9: "owned", tag:sigs.k8s.io/cluster-api-provider-aws/role: "common"] - would remove
Scan complete: 5 total, 5 nukeable, 0 filtered.
```

I would expect *only* resources tagged with sigs.k8s.io/cluster-api-provider-aws/cluster/* should be deleted. Is this how inverting works?

Thanks

**Comment by ekristen** [comment]
Unfortunately the `type` applies to how the value is applied in the filter. Property names are exact matches. Essentially as written your filter is looking for a specific tag of `tag:sigs.k8s.io/cluster-api-provider-aws/cluster/*` instead of `tag:sigs.k8s.io/cluster-api-provider-aws/cluster/capick8s-create-2ij5h1` and then cannot find a matching property and so will never filter, inverted or not.

```yaml
- property: tag:sigs.k8s.io/cluster-api-provider-aws/cluster/capick8s-create-2ij5h1
   type: exact
   value: owned
   invert: true
```
