### ISSUE TITLE
TLS handshake timeout While Listing CodeStarProject 

### ISSUE THREAD

**Issue by fitzwaterb** [ekristen/aws-nuke#310]
```
level=error msg="Listing CodeStarProject failed:\n    RequestError: send request failed\n    caused by: Post \"https://codestar.us-east-1.amazonaws.com/\": net/http: TLS handshake timeout" error="RequestError: send request failed\ncaused by: Post \"https://codestar.us-east-1.amazonaws.com/\": net/http: TLS handshake timeout"
```

On almost half of the accounts I've tried to nuke, this timeout error has caused aws-nuke to stop and cannot complete a dry-run. To the best of my knowledge, we've never used CodeStar and I do not understand why this happens on some accounts but not all accounts.

**Comment by ekristen** [comment]
If you don't use it, just exclude it in your configuration. See if that allows it to complete.

**Comment by ekristen** [comment]
Please provide your configuration. You should exclude any resource you know you don't ever use. Unless you know you want it, you should also exclude `S3Object`

**Comment by fitzwaterb** [comment]
Excluding S3Object appears to have worked.

configuration:

```yaml
regions:
  - global
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2

accounts:
  111111111111:
   presets:
     - common

bypass-alias-check-accounts:
  - 111111111111

settings:
  EC2Instance:
    DisableDeletionProtection: true
  RDSInstance:
    DisableDeletionProtection: true

resource-types:
  excludes:
    - S3Object
    - CodeStarProject
    - CodeStarConnection
    - CodeStarNotificationRule
    - OpsWorksLayer
    - OpsWorksInstance
    - OpsWorksCMServerState
    - OpsWorksApp
    - OpsWorksCMBackup
    - OpsWorksCMServer
    - OpsWorksUserProfile
    - FMSPolicy
    - FMSNotificationChannel
    - CloudSearchDomain
    - MachineLearningEvaluation
    - MachineLearningMLModel
    - MachineLearningDataSource
    - MachineLearningBranchPrediction
    - RoboMakerSimulationApplication
    - RoboMakerRobotApplication
    - RoboMakerSimulationJob

presets:
  common:
    filters:
      IAMRole:
        - aws-nuke-role
      IAMRolePolicyAttachment:
        - "aws-nuke-role -> AdministratorAccess"
 ```
