### ISSUE TITLE
Not able to configure a filter for resources of type "ECSTask"

### ISSUE THREAD

**Issue by m-jonn** [ekristen/aws-nuke#317]
Hi,

somehow I am not able to provide the right filter for ECSTasks.

Tried many ways to write the filter:
``` yaml
accounts:
  "000011112222":
    filters:
       ECSTask:
          - "[ClusterARN: \"arn:aws:ecs:us-east-1:...\", TaskARN: \"arn:aws:ecs:us-east-1:.../75e3fdd99daf49cf9d3fd3ba5c9ea341\"]"
          - "75e3fdd99daf49cf9d3fd3ba5c9ea341"
          - "arn:aws:ecs:us-east-1:../75e3fdd99daf49cf9d3fd3ba5c9ea341"
```
However, the result is always the same:
`us-east-1 - ECSTask - [ClusterARN: "arn:aws:ecs:us-east-1:...", TaskARN: "arn:aws:ecs:us-east-1:.../75e3fdd99daf49cf9d3fd3ba5c9ea341"] - would remove`

What would be a proper way of filtering ECSTasks?

**Comment by ekristen** [comment]
Assuming the output is 100% correct, it looks like there is no `String()` output, so your items `75e3fdd99daf49cf9d3fd3ba5c9ea341` and `arn:aws:ecs:us-east-1:../75e3fdd99daf49cf9d3fd3ba5c9ea341` will never match, therefore you have to use properties.

The reason they won't match is because `- "75e3fdd99daf49cf9d3fd3ba5c9ea341"` is an `Exact` match against the `String()` output of the resource.

```yaml
accounts:
  "000011112222":
    filters:
       ECSTask:
          - property: ClusterARN
            type: equal
            value: arn:aws:ecs:us-east-1:../75e3fdd99daf49cf9d3fd3ba5c9ea341
```

OR you can use a different type like `glob`

```yaml
accounts:
  "000011112222":
    filters:
       ECSTask:
          - property: ClusterARN
            type: glob
            value: *75e3fdd99daf49cf9d3fd3ba5c9ea341*
```
