### ISSUE TITLE
How does one debug when aws-nuke 3 hangs?

### ISSUE THREAD

**Issue by queue-tip** [ekristen/aws-nuke#355]
I have migrated a config file to version 3 syntax. It specifies the `global`, `us-east-1`, `us-east-2`, `us-west-1`, and `us-west-2` regions.

When testing with the latest aws-nuke 3.x version, it seems to hang when it gets to us-east-1. I have set the log-level to debug and moved us-east-1 to the end of the regions list but it looks like it gets stuck at the same place.

Is there a better way to debug what's happening?

**Comment by ekristen** [comment]
`-l trace` -- it's doubtful it's hanging, it's likely iterating over objects, currently there's no feedback on object iteration.

Do you have `S3Object` excluded?

**Comment by queue-tip** [comment]
Thanks for responding so quickly.

No, I don't have that resource type excluded. Is version 3 expected to take much longer at iterating over S3Objects than version 2? Version 2.26.6 completes the dry-run.

I set the log level to trace when I started the dry-run in the same account again minutes after you replied. According to the trace, the last request was sent 78 minutes ago.

**Comment by ekristen** [comment]
@queue-tip please provide your configuration and version running.

In the mean time try excluding `S3Object`.  `--exclude S3Object` or modify your config. 

It's possible you hit a bug, we will have to work through process of elimination to know for sure.

**Comment by vinhltr** [comment]
I'm having a similar experience with regards to S3Object just this past week.

In my sandbox env, there is an access log bucket with roughly 60k objects, this is from a single bucket. I'd estimate the grand total for all existing buckets would be roughly 65k objects. This causes a golang deadlock error when iterating over the S3Object resources. I then tried to empty the access log bucket, and retry the aws-nuke cli again, and it worked.

<img width="1781" alt="Screenshot 2024-10-01 at 8 50 44 AM" src="https://github.com/user-attachments/assets/9f52be89-ef87-4080-b0ab-ddf4a0c992a2">

Some more context, my config regarding S3Object does not really filter anything. And this is also the first time I've seen this issue, and I've been using aws-nuke (old repo & this fork) for almost a year now.

version: 3.24.0

**Comment by queue-tip** [comment]
> @queue-tip please provide your configuration and version running.
> 
> In the mean time try excluding `S3Object`. `--exclude S3Object` or modify your config.
> 
> It's possible you hit a bug, we will have to work through process of elimination to know for sure.

With the exception of the account numbers, this is the config file. I've experienced the same behavior with versions
- `3.21.0`
- `3.24.0`

```yaml
---
settings:
  RDSInstance:
    disable-deletion-protection: true
  EC2Instance:
    disable-deletion-protection: true
  CloudformationStack:
    disable-deletion-protection: true

resource-types:
  excludes:
    - AmazonML
    - FMSNotificationChannel
    - FMSPolicy
    - Cloud9Environment
    - CloudSearchDomain
    - CodeStarProject
    - MachineLearningBranchPrediction
    - MachineLearningDataSource
    - MachineLearningEvaluation
    - MachineLearningMLModel
    - CodeStarProject
    - OpsWorksApp
    - OpsWorksCMBackup
    - OpsWorksCMServer
    - OpsWorksCMServerState
    - OpsWorksInstance
    - OpsWorksLayer
    - OpsWorksUserProfile
    - RoboMakerRobotApplication
    - RoboMakerSimulationApplication
    - RoboMakerSimulationJob

regions:
  - global
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2

blocklist:
  - "000000000001"
  - "000000000002"

accounts:

  "000000000003":
    presets:
      - "base_config"
      - "common"
      - "dns"
      - "sso"

  "000000000004":
    presets:
      - "base_config"
      - "common"
      - "sso"

presets:
  common:
    filters:
      CloudTrailTrail:
        - "cloudtrail-events-org"
      EC2DefaultSecurityGroupRule:
        - property: SecurityGroupId
          type: glob
          value: "*"
      EC2DHCPOption:
        - property: DefaultVPC
          value: "true"
      EC2InternetGateway:
        - property: DefaultVPC
          value: "true"
      EC2InternetGatewayAttachment:
        - property: DefaultVPC
          value: "true"
      EC2RouteTable:
        - property: DefaultVPC
          value: "true"
      EC2Subnet:
        - property: DefaultVPC
          value: "true"
      EC2VPC:
        - property: IsDefault
          value: "true"
      IAMVirtualMFADevice:
        - type: regex
          value: "arn:aws:iam::\\d{12}:mfa/.*"
      OSPackage:
        - property: PackageName
          type: glob
          value: "*"
      SSMParameter:
        - "/builtins/api_key"

  sso:
    filters:
      IAMRole:
        - "OrganizationAccountAccessRole"
        - type: "glob"
          value: "AWSReservedSSO_*"
      IAMRolePolicyAttachment:
        - OrganizationAccountAccessRole -> AdministratorAccess
        - type: "glob"
          value: "AWSReservedSSO_*"
      IAMSAMLProvider:
        - type: glob
          value: "*:saml-provider/AWSSSO_*_DO_NOT_DELETE"

  base_config:
    filters:
      IAMRole:
        - "platform-deployer"
        - "platform-admin"
      IAMRolePolicyAttachment:
        - "platform-deployer -> AdministratorAccess"
        - "platform-admin -> AdministratorAccess"

  dns:
    filters:
      Route53HostedZone:
        - type: regex
          value: ".*\\.example\\.com"
      SSMParameter:
        - "/production/route53/subdomain_zone_id"
```
