### ISSUE TITLE
Account Filter Recognition Failure

### ISSUE THREAD

**Issue by JL7105** [ekristen/aws-nuke#382]
I am attempting to nuke every resource I can in every region except one IAM user. I have followed the account filter doucmentation as best as I could. 

```
regions:
  - all

  
accounts:
  ############:
    filters:
      IAMUser:
        - "******************"  
```

Note: The account ID and IAM user is filled in correctly when ran. I have triple checked.

Here is the result I get every time:

    Configuration Details
    
    Account ID:       ############
    Resource Types:   505 (total)
          Included:   505
          Excluded:   0
    Filter Presets:   0
    Resource Filters: 0
    
    Note: use --with-filtered to see resources with filters defined
    Note: use --with-included to see included resource types that will be nuked
    Note: use --with-excluded to see excluded resource types

Are there any fixes or work arounds for this? It seems to recognize the file and the regions just not the account filter I have in place.
