### ISSUE TITLE
When property is not set.

### ISSUE THREAD

**Issue by YuriGal** [ekristen/aws-nuke#383]
I am targeting IAM roles that either haven't been used in a while, or haven't been used at all. The first one is pretty straightfoward:

```yaml
resource-types:
  targets:
  - IAMRole
filters:
  IAMRole:
    - type: dateOlderThan
      property: LastUsedDate
      value: 8766h # 1 year
```
But is there a way to target a role where `LastUsedDate` is not set at all?
