### ISSUE TITLE
Feedback Wanted!

### ISSUE THREAD

**Issue by ekristen** [ekristen/aws-nuke#389]
Please provide your feedback. Here are some of the issues.

- #298 
- #388

**Comment by ekristen** [comment]
@eaudetcobello I'm considering adding a feature to flip from exclusion to inclusion via https://github.com/ekristen/aws-nuke/issues/327 -- there's much to consider with adding this behavior.

**Comment by BwL1289** [comment]
Exclude all AWS managed IAM policies as well as resources created by CDK. Essentially, reset the AWS account to how it was at initial creation.

I can't tell from the documentation whether all AWS managed IAM policies are automatically ignored.

**Comment by ekristen** [comment]
@BwL1289 and @eaudetcobello you can sort of already filter for removal using [Global Filters Feature](https://ekristen.github.io/aws-nuke/features/global-filters/) combined with the `invert` flag, but it would only work with a single tag, with [Filter Groups](https://ekristen.github.io/aws-nuke/config-filtering/#filter-groups) you could possible extend this further.

**Comment by BwL1289** [comment]
@ekristen a technique I'm using for CDK is:

```yaml
presets:
  # Exclude cdk resources from being nuked
  cdk:
    filters:
      # Exclude resources with cdk in the name
      __global__: # Catch all for all resources
        - type: "contains"
          value: "cdk"
        - type: glob
          value: "*cdk*"
        - property: Name
          type: "glob"
          value: "*cdk*"
        - property: ARN
          type: "glob"
          value: "*cdk*"
        - property: tag:aws:cloudformation:stack-name
          value: "CDKToolkit"
```

Should this work as I expect?
