### ISSUE TITLE
Global filter not working as expected

### ISSUE THREAD

**Issue by eaudetcobello** [ekristen/aws-nuke#395]
v3.28

Here is the EC2Address's tags:
![image](https://github.com/user-attachments/assets/26d7dd48-e4a7-483f-91a1-cbbcabf35a58)

When I use the `common` preset, the resource is excluded *as expected*. However, when I use the `__global__` filter, I expect the behaviour to be identical (resource should be filtered), but the resource is marked for deletion.

```
__global__:
  - property: tag:Name
    type: glob
    value: ck8scapi*

presets:
  common:
    filters:
      EC2Address:
        - property: tag:Name
          type: glob
          value: "ck8scapi*"

resource-types:
    includes:
      - EC2Instance

accounts:
  0183023xxxx:
    presets:
      - common
```
