### ISSUE TITLE
aws-nuke not finishing? freezes? stuck?

### ISSUE THREAD

**Issue by LarsPeterson** [ekristen/aws-nuke#404]
What am I doing wrong here? It seems the process never completes and freezes at the same spot every time. Waited for over an hour with no change or additional output. Ran over and over with the same result. I am using version `aws-nuke-v3.29.1-windows-amd64`.

I start the process with this command:

```
$ AWS_PROFILE=root ./aws-nuke.exe run -c ./config/nuke-config.yaml
```

Here is my configuration:

```
regions:
  - "global" # This is for all global resource types e.g. IAM
  - "us-east-2"
  - "us-east-1"
  - "us-west-1"
  - "us-west-2"
  - "af-south-1"
  - "ap-east-1"
  - "ap-south-1"
  - "ap-northeast-3"
  - "ap-northeast-2"
  - "ap-southeast-1"
  - "ap-southeast-2"
  - "ap-northeast-1"
  - "ca-central-1"
  - "cn-north-1"
  - "cn-northwest-1"
  - "eu-central-1"
  - "eu-west-1"
  - "eu-west-2"
  - "eu-south-1"
  - "eu-west-3"
  - "eu-north-1"
  - "me-south-1"
  - "sa-east-1"

blocklist:
- "999999999999" # production

accounts:
  "837227442836":
    presets:
      - "kis-strapi-bucket"
      - "pd-strapi-bucket"

presets:

  kis-strapi-bucket:
    filters:
      S3Object:
      - type: regex
        value: "s3://kis-strapi-bucket/.*"
      S3Bucket:
      - type: regex
        value: "kis-strapi-bucket"

  pd-strapi-bucket:
    filters:
      S3Object:
      - type: regex
        value: "s3://pd-strapi-bucket/.*"
      S3Bucket:
      - type: regex
        value: "pd-strapi-bucket"
```

Here is the output, just the last few lines, where it is freezing/stuck:

```
us-east-1 - OSPackage - G82836011 - [CreatedTime: "2024-09-10T15:56:45Z", PackageID: "G82836011", PackageName: "analysis-sudachi"] - cannot delete default opensearch packages
us-east-1 - OSPackage - G86156528 - [CreatedTime: "2023-10-12T22:54:58Z", PackageID: "G86156528", PackageName: "analysis-sudachi"] - cannot delete default opensearch packages
us-east-1 - OSPackage - G88141368 - [CreatedTime: "2023-10-12T20:31:16Z", PackageID: "G88141368", PackageName: "analysis-pinyin"] - cannot delete default opensearch packages
us-east-1 - MemoryDBParameterGroup - default.memorydb-redis6 - [Family: "memorydb_redis6", Name: "default.memorydb-redis6"] - cannot delete default parameter group
us-east-1 - MemoryDBParameterGroup - default.memorydb-redis7 - [Family: "memorydb_redis7", Name: "default.memorydb-redis7"] - cannot delete default parameter group
us-east-1 - MemoryDBParameterGroup - default.memorydb-redis7.search - [Family: "memorydb_redis7", Name: "default.memorydb-redis7.search"] - cannot delete default parameter group
us-east-1 - MemoryDBParameterGroup - default.memorydb-redis7.search.preview - [Family: "memorydb_redis7.search.preview", Name: "default.memorydb-redis7.search.preview"] - cannot delete default parameter group
us-east-1 - MemoryDBParameterGroup - default.memorydb-valkey7 - [Family: "memorydb_valkey7", Name: "default.memorydb-valkey7"] - cannot delete default parameter group
us-east-1 - MemoryDBParameterGroup - default.memorydb-valkey7.search - [Family: "memorydb_valkey7", Name: "default.memorydb-valkey7.search"] - cannot delete default parameter group
time="2024-11-03T02:16:44-06:00" level=error msg="Listing RekognitionProject failed:\n    AccessDeniedException: " error="AccessDeniedException: "
time="2024-11-03T02:16:44-06:00" level=error msg="Listing OpsWorksApp failed:\n    AccessDeniedException: AWS OpsWorks Stacks is no longer accepting new customers\n    \tstatus code: 400, request id: db99bd4d-3984-4310-8be7-ad42760cd7d1" error="AccessDeniedException: A
WS OpsWorks Stacks is no longer accepting new customers\n\tstatus code: 400, request id: db99bd4d-3984-4310-8be7-ad42760cd7d1"
time="2024-11-03T02:16:45-06:00" level=error msg="Listing CloudSearchDomain failed:\n    NotAuthorized: New domain creation not supported on this account. Please reach out to AWS Support for assistance.\n    \tstatus code: 401, request id: a2441cd4-fd6d-40a0-bb73-1faa7
8d15ada" error="NotAuthorized: New domain creation not supported on this account. Please reach out to AWS Support for assistance.\n\tstatus code: 401, request id: a2441cd4-fd6d-40a0-bb73-1faa78d15ada"
time="2024-11-03T02:16:46-06:00" level=info msg="TagOptionNotMigratedException: TagOption Migration not complete"
time="2024-11-03T02:16:46-06:00" level=error msg="Listing FMSPolicy failed:\n    AccessDeniedException: No default admin could be found for account 837227442836 in Region us-west-1\n    \tstatus code: 400, request id: 14973597-f62a-4cb4-8837-1dc70fc3d713" error="Access
DeniedException: No default admin could be found for account 837227442836 in Region us-west-1\n\tstatus code: 400, request id: 14973597-f62a-4cb4-8837-1dc70fc3d713"
time="2024-11-03T02:16:47-06:00" level=error msg="Listing FMSNotificationChannel failed:\n    AccessDeniedException: No default admin could be found for account 837227442836 in Region us-west-1\n    \tstatus code: 400, request id: 4c194548-5e09-48db-805a-072c634804c5"
error="AccessDeniedException: No default admin could be found for account 837227442836 in Region us-west-1\n\tstatus code: 400, request id: 4c194548-5e09-48db-805a-072c634804c5"
time="2024-11-03T02:16:47-06:00" level=error msg="Listing OpsWorksCMServerState failed:\n    ValidationException: AWS OpsWorks CM is not accepting new customers. This command is therefore no longer supported." error="ValidationException: AWS OpsWorks CM is not acceptin
g new customers. This command is therefore no longer supported."
time="2024-11-03T02:16:47-06:00" level=error msg="Listing Cloud9Environment failed:\n    AccessDeniedException: This account does not have access to the Cloud9 service\n    \tstatus code: 400, request id: 05419349-1014-4f2f-8996-68fd7d2c5499" error="AccessDeniedExcepti
on: This account does not have access to the Cloud9 service\n\tstatus code: 400, request id: 05419349-1014-4f2f-8996-68fd7d2c5499"
time="2024-11-03T02:16:47-06:00" level=error msg="Listing OpsWorksUserProfile failed:\n    AccessDeniedException: AWS OpsWorks Stacks is no longer accepting new customers\n    \tstatus code: 400, request id: 06c4a2ac-e227-4de1-b0fb-7bf672c281ca" error="AccessDeniedExce
ption: AWS OpsWorks Stacks is no longer accepting new customers\n\tstatus code: 400, request id: 06c4a2ac-e227-4de1-b0fb-7bf672c281ca"
time="2024-11-03T02:16:47-06:00" level=error msg="Listing OpsWorksCMServer failed:\n    ValidationException: AWS OpsWorks CM is not accepting new customers. This command is therefore no longer supported." error="ValidationException: AWS OpsWorks CM is not accepting new
 customers. This command is therefore no longer supported."
time="2024-11-03T02:16:48-06:00" level=error msg="Listing OpsWorksCMBackup failed:\n    ValidationException: AWS OpsWorks CM is not accepting new customers. This command is therefore no longer supported." error="ValidationException: AWS OpsWorks CM is not accepting new
 customers. This command is therefore no longer supported."
time="2024-11-03T02:16:48-06:00" level=info msg="TagOptionNotMigratedException: TagOption Migration not complete"
time="2024-11-03T02:16:48-06:00" level=error msg="Listing RekognitionDataset failed:\n    AccessDeniedException: " error="AccessDeniedException: "
time="2024-11-03T02:16:49-06:00" level=error msg="Listing OpsWorksLayer failed:\n    AccessDeniedException: AWS OpsWorks Stacks is no longer accepting new customers\n    \tstatus code: 400, request id: 250c9ee3-32a0-4171-a15b-1b44c0f1fce9" error="AccessDeniedException:
 AWS OpsWorks Stacks is no longer accepting new customers\n\tstatus code: 400, request id: 250c9ee3-32a0-4171-a15b-1b44c0f1fce9"
time="2024-11-03T02:16:49-06:00" level=error msg="Listing OpsWorksInstance failed:\n    AccessDeniedException: AWS OpsWorks Stacks is no longer accepting new customers\n    \tstatus code: 400, request id: 4d62e32b-34a4-40bb-9a50-22ee9624a616" error="AccessDeniedExcepti
on: AWS OpsWorks Stacks is no longer accepting new customers\n\tstatus code: 400, request id: 4d62e32b-34a4-40bb-9a50-22ee9624a616"
time="2024-11-03T02:18:12-06:00" level=error msg="Listing CodeStarProject failed:\n    RequestError: send request failed\n    caused by: Post \"https://codestar.us-west-1.amazonaws.com/\": dial tcp 176.32.119.241:443: connectex: A connection attempt failed because the
connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." error="RequestError: send request failed\ncaused by: Post \"https://codestar.us-west-1.amazonaws.com/\": dial tcp 176.32.119
.241:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
```

How can I troubleshoot this?
Are there more inclusive log files I can read?
No idea how to proceed.

**Comment by ekristen** [comment]
So based on your configuration you are wanting to keep the entire bucket `kis-strapi-bucket` and `pd-strapi-bucket` ...

I would change your regions to just `- all` this way you don't need to list them. Since you are keeping those buckets, I would remove the S3Object filter and disable the S3Object use entirely. 

Please see the warning about **NOT** using S3Object. https://ekristen.github.io/aws-nuke/resources/s3-object/

**Comment by LarsPeterson** [comment]
Thank you for your quick response. Even after listing the `S3Bucket` and `S3Object` excludes with the following config, I still had issues with it freezing.

```
resource-types:
  excludes:
    - S3Bucket
    - S3Object
```

After I replicated the full starter configuration, I was able to see it complete successfully. Maybe all the deprecated services in AWS were causing it to hang up/freeze/get stuck? I don't know.

```
regions:
  - "all"

blocklist:
- "999999999999" # production

settings:
  EC2Image:
    IncludeDisabled: true
    IncludeDeprecated: true
    DisableDeregistrationProtection: true
  EC2Instance:
    DisableStopProtection: true
    DisableDeletionProtection: true
  RDSInstance:
    DisableDeletionProtection: true
  CloudFormationStack:
    DisableDeletionProtection: true
  DynamoDBTable:
    DisableDeletionProtection: true

resource-types:
  excludes:
    - S3Bucket
    - S3Object # Excluded because S3 bucket removal handles removing all S3Objects
    - ServiceCatalogTagOption # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - ServiceCatalogTagOptionPortfolioAttachment # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - FMSNotificationChannel # Excluded because it's not available
    - FMSPolicy # Excluded because it's not available
    - MachineLearningMLModel # Excluded due to ML being unavailable
    - MachineLearningDataSource # Excluded due to ML being unavailable
    - MachineLearningBranchPrediction # Excluded due to ML being unavailable
    - MachineLearningEvaluation # Excluded due to ML being unavailable
    - RoboMakerDeploymentJob # Deprecated Service
    - RoboMakerFleet # Deprecated Service
    - RoboMakerRobot # Deprecated Service
    - RoboMakerSimulationJob
    - RoboMakerRobotApplication
    - RoboMakerSimulationApplication
    - OpsWorksApp # Deprecated service
    - OpsWorksInstance # Deprecated service
    - OpsWorksLayer # Deprecated service
    - OpsWorksUserProfile # Deprecated service
    - OpsWorksCMBackup # Deprecated service
    - OpsWorksCMServer # Deprecated service
    - OpsWorksCMServerState # Deprecated service
    - CodeStarProject # Deprecated service
    - CodeStarConnection # Deprecated service
    - CodeStarNotification # Deprecated service
    - Cloud9Environment # Deprecated service
    - CloudSearchDomain # Deprecated service
    - RedshiftServerlessSnapshot # Deprecated service
    - RedshiftServerlessNamespace # Deprecated service
    - RedshiftServerlessWorkgroup # Deprecated service

presets:
  defaults:
    filters:
      EC2Subnet:
        - property: DefaultVPC
          value: "true"
      EC2DefaultSecurityGroupRule:
        - property: DefaultVPC
          value: "true"
      EC2DHCPOption:
        - property: DefaultVPC
          value: "true"
      EC2VPC:
        - property: IsDefault
          value: "true"
      EC2InternetGateway:
        - property: DefaultVPC
          value: "true"
      EC2InternetGatewayAttachment:
        - property: DefaultVPC
          value: "true"

accounts:
  '837227442836':
    presets:
      - defaults
```

But everything seems to be working now. Sincerely appreciate your fast help. Thank you.
