### ISSUE TITLE
__global__ filters resulting in fatal error `*resources.xyz does not support custom properties`

### ISSUE THREAD

**Issue by zack-is-cool** [ekristen/aws-nuke#406]
I'm trying to filter globally using tags:

```yaml
accounts:
  "999999999999":
    filters:
      __global__:
        - property: "tag:Nuke"
          value: "false"
```

My assumption is that this would look for everything that has tags and exclude that, but it seems like this is filtering and throwing errors on resources that don't support properties.

This is from multiple different runs after excluding resources each time

```
*resources.BackupVaultAccessPolicy does not support custom properties
*resources.ResourceExplorer2Index does not support custom properties
*resources.DirectoryServiceDirectory does not support custom properties```

Do globals only work if you exclude anything that can't have properties? I'm not sure I'm configuring this properly.
