### ISSUE TITLE
SFNStateMachine Tag Support

### ISSUE THREAD

**Issue by andrew-squire** [ekristen/aws-nuke#415]
Hi,
We're currently utilising the `__global__` filter for excluding resources with tags, which is working on the most part *apart* from SFNStateMachine. (Similar issue raised [here](https://github.com/ekristen/aws-nuke/issues/110))

Config file:
```
    filters:
      __global__:
        - property: tag:DoNotNuke
          value: "True"
        - property: tag:DoNotNuke
          value: "true"
```

State machine tags:
![image](https://github.com/user-attachments/assets/c4a5d810-b925-4581-a79b-b944d173faa5)

Dry run results:
```
us-east-1 - SFNStateMachine - arn:aws:states:us-east-1:<redacted>:stateMachine:self-aws-nuke - would remove
```

Hopefully an easy fix, thanks!
