### ISSUE TITLE
Docker Image with Gitlab panic: runtime error: invalid memory address or nil pointer dereference [recovered]

### ISSUE THREAD

**Issue by adamLShine** [ekristen/aws-nuke#417]
I'm have set up a Gitlab Pipeline using the published Docker image, however whenever I try to run the aws nuke commands I recieve the following errors? My AWS access key and secret key have been assigned to the env vars $AWS_ACCESS_KEY_ID and  $AWS_SECRET_ACCESS_KEY. 

I looked through the documentation and don't know why this is failing. When I used the 'explain-account' command everything works fine. 

<img width="865" alt="Screenshot 2024-11-13 at 7 13 13 PM" src="https://github.com/user-attachments/assets/2e673bb7-4224-4e44-acd9-3cba3eeed140">
<img width="841" alt="Screenshot 2024-11-13 at 7 18 51 PM" src="https://github.com/user-attachments/assets/4af94aa7-caf3-489d-82c2-191317f57934">

**Comment by ekristen** [comment]
@adamLShine please share your config.

**Comment by ekristen** [comment]
What version were you using?

**Comment by adamLShine** [comment]
I tried the latest two versions of the image

*Adam Langdon*
Engineer
m: 0404788931 <//0404788931>
e: ***@***.***
[image: shinesolutions.com] <https://shinesolutions.com>

**Comment by ekristen** [comment]
Without more logs, impossible to say, my guess is that it's a config bug, one of which I recently fixed and is in the very latest version of the tool. 

1. I need the entire stack track output
2. I need your configuration
3. I need the version it's still happening on

**Comment by ekristen** [comment]
Your configuration is not properly formatted. If you'd copy and paste your config in instead of a screenshot I'll fix for you.

filters need to be indented undernearth the account. That should have been fixed by the latest patch release, I will have to test your specific configuration format.

**Comment by adamLShine** [comment]
blocklist:
- "000000000" 

accounts:
  "0000000000": 
  filters:
    __global__:
      - property: tag:aws-nuke
        value: "Disable"
      - property: tag:aws-nuke
        value: "disable"


Thank you!

**Comment by ekristen** [comment]
You should use [codefences](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

```yaml
regions:
  - global
  - us-east-1
  - ap-southeast-2

blocklist:
  - "000000000000" 

accounts:
  "012345678912": 
    filters:
      __global__:
        - property: tag:aws-nuke
          value: "Disable"
        - property: tag:aws-nuke
          value: "disable"
```
