### ISSUE TITLE
Delete all AWS resources in an account based on a specific tag is failing.

### ISSUE THREAD

**Issue by Muru-777** [ekristen/aws-nuke#463]
I am trying to delete all AWS resources in an account based on a specific tag (e.g., tag:release-environment with value val-157373). The job is running in a GitLab pipeline, but it frequently encounters the following error. The process reaches this point, gets stuck and does not proceed further.

time="2024-12-17T10:38:09Z" level=error msg="listing failed:\n    RequestError: send request failed\n    caused by: Post \"https://**codestar.eu-west-1.amazonaws.com/\": dial tcp 22.218.139:443: i/o timeout" error="RequestError: send request failed\ncaused by: Post \"https://codestar.eu-west-1.amazonaws.com/\": dial tcp 22.218.139:443: i/o timeout" owner=eu-west-1 resource_type=CodeStarProject**

**nuke-config.yaml:**
```
regions:
  - global
  - eu-west-1

blocklist:
  - ""

presets:
  common:
    filters:
      __global__:
        - property: tag:release-environment
          value: "val-157373"

accounts:
  <account_id>:
    presets:
      - common
```

gitlab-pipeline.yaml:
```
aws-nuke:
  stage: nuke
  image: <aws_account_id>.dkr.ecr.eu-west-1.amazonaws.com/ghcr/ekristen/aws-nuke:v3.36.0
  variables:
    AWS_ASSUME_ROLE_ARN: arn:aws:iam::<aws_account_id>:role/cleanup-iam-role-nuke
  script:
    - aws-nuke version
    - aws-nuke nuke -c aws-nuke-config.yaml --force --force-sleep 3
  rules:
    - when: always
  tags:
    - big
```

**Comment by ekristen** [comment]
It's not stuck on that error, that error can be safely ignored. I recommend using this starter config and modify to your needs. https://aws-nuke.ekristen.dev/starter-config/.

Likely it's hanging up on either S3Object or CloudWatchLogGroups. You can turn on debug logging and find out for sure, the latest version tells you what it's currently iterating. You should 99% disable `S3Object`. (i.e. exclude)

**Comment by ekristen** [comment]
It's not stuck on that error, that error can be safely ignored. I recommend using this starter config and modify to your needs. https://aws-nuke.ekristen.dev/starter-config/.

Likely it's hanging up on either S3Object or CloudWatchLogGroups. You can turn on debug logging and find out for sure, the latest version tells you what it's currently iterating. You should 99% disable `S3Object`. (i.e. exclude)

**Comment by Muru-777** [comment]
@ekristen That helps, but from my configuration it is not fetching the AWS resources in an account based on a specific tag.

```
project:
    filters:
      __global__:
        - property: tag:release-environment
          value: "val-157373"

accounts:
  "<account>":
    presets:
      - common
      - organization
      - defaults
      - project
```

I am trying to delete all AWS resources in an account based on a specific tag (e.g., tag:release-environment with value val-157373). Is it possible to achieve this using a global filter?
