### ISSUE TITLE
IAM Roles and policies are not getting deleted.

### ISSUE THREAD

**Issue by Muru-777** [ekristen/aws-nuke#464]
@ekristen  I am trying to delete all AWS resources in an account based on a specific tag (e.g., tag:release-environment with value val-157373). Apart from IAM, all the resources are deleted and IAM roles, policies are failing with below error.

Could see val-158261-intermediatedemo-dotnet-intermediate-demo-api-vpc  and val-158261-intermediatedemo-dotnet-intermediate-demo-api-logs policies are attached to role val-158261-intermediatedemo-dotnet-intermediate-demo-api, val-158261-iam-policy-deploy-dotnet_sample_intermediate-0 and val-158261-iam-policy-deploy-dotnet_sample_intermediate-1 policies are attached to val-158261-iam-role-deploy-65.
I have verified there is no permission boundary set for the policies(https://github.com/ekristen/aws-nuke/issues/203).

```
time="2024-12-18T11:05:23Z" level=error msg="There are resources in failed state, but none are ready for deletion, anymore."
global - IAMPolicy - arn:aws:iam:: :policy/val-158261-intermediatedemo-dotnet-intermediate-demo-api-vpc - [ARN: "arn:aws:iam:: :policy/val-158261-intermediatedemo-dotnet-intermediate-demo-api-vpc"] - failed
time="2024-12-18T11:05:23Z" level=error msg="DeleteConflict: Cannot delete a policy attached to entities.\n\tstatus code: 409, request id: cc956549-a714-41bc-b957-197c7b1f73b9"
global - IAMPolicy - arn:aws:iam:: :policy/val-158261-iam-policy-deploy-dotnet_sample_intermediate-0 - [ARN: "arn:aws:iam:: :policy/val-158261-iam-policy-deploy-dotnet_sample_intermediate-0"] - failed
time="2024-12-18T11:05:23Z" level=error msg="DeleteConflict: Cannot delete a policy attached to entities.\n\tstatus code: 409, request id: a99c629b-235a-483b-acb7-610bff3fd000"
global - IAMPolicy - arn:aws:iam:: :policy/val-158261-intermediatedemo-dotnet-intermediate-demo-api-logs - [ARN: "arn:aws:iam:: :policy/val-158261-intermediatedemo-dotnet-intermediate-demo-api-logs"] - failed
time="2024-12-18T11:05:23Z" level=error msg="DeleteConflict: Cannot delete a policy attached to entities.\n\tstatus code: 409, request id: d1f77328-2eba-452b-b76a-d1f0f3630d2e"
global - IAMPolicy - arn:aws:iam:: :policy/val-158261-iam-policy-deploy-dotnet_sample_intermediate-1 - [ARN: "arn:aws:iam:: :policy/val-158261-iam-policy-deploy-dotnet_sample_intermediate-1"] - failed
time="2024-12-18T11:05:23Z" level=error msg="DeleteConflict: **Cannot delete a policy attached to entities.\n\tstatus code: 409, request id: 174add9a-67e6-4c48-954a-ec0bfce43a4f"**
global - IAMRole - val-158261-iam-role-deploy-65 - [CreateDate: "2024-12-18T09:01:42Z", LastUsedDate: "2024-12-18T09:03:33Z", Name: "val-158261-iam-role-deploy-65"] - failed
time="2024-12-18T11:05:23Z" level=error msg="DeleteConflict: Cannot delete entity, must detach all policies first.\n\tstatus code: 409, request id: d9edcb30-bfa0-4f99-9348-6d29ad4ae176"
global - IAMRole - val-158261-intermediatedemo-dotnet-intermediate-demo-api - [CreateDate: "2024-12-18T09:03:17Z", LastUsedDate: "2024-12-18T09:03:17Z", Name: "val-158261-intermediatedemo-dotnet-intermediate-demo-api"] - failed
time="2024-12-18T11:05:23Z" level=error **msg="DeleteConflict: Cannot delete entity, must detach all policies first.**\n\tstatus code: 409, request id: 1ea6aea3-b593-499a-b66f-772f6881ac67"
```

aws-nuke-config.yaml:

```
regions:
  - global
  - eu-west-1

blocklist:
  - ""

settings:
  EC2Image:
    IncludeDisabled: true
    IncludeDeprecated: true
    DisableDeregistrationProtection: true
  EC2Instance:
    DisableStopProtection: true
    DisableDeletionProtection: true
  RDSInstance:
    DisableDeletionProtection: true
  CloudFormationStack:
    DisableDeletionProtection: true
  DynamoDBTable:
    DisableDeletionProtection: true

resource-types:
  excludes:
    - S3Object # Excluded because S3 bucket removal handles removing all S3Objects
    - ServiceCatalogTagOption # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - ServiceCatalogTagOptionPortfolioAttachment # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - FMSNotificationChannel # Excluded because it's not available
    - FMSPolicy # Excluded because it's not available
    - MachineLearningMLModel # Excluded due to ML being unavailable
    - MachineLearningDataSource # Excluded due to ML being unavailable
    - MachineLearningBranchPrediction # Excluded due to ML being unavailable
    - MachineLearningEvaluation # Excluded due to ML being unavailable
    - RoboMakerDeploymentJob # Deprecated Service
    - RoboMakerFleet # Deprecated Service
    - RoboMakerRobot # Deprecated Service
    - RoboMakerSimulationJob
    - RoboMakerRobotApplication
    - RoboMakerSimulationApplication
    - OpsWorksApp # Deprecated service
    - OpsWorksInstance # Deprecated service
    - OpsWorksLayer # Deprecated service
    - OpsWorksUserProfile # Deprecated service
    - OpsWorksCMBackup # Deprecated service
    - OpsWorksCMServer # Deprecated service
    - OpsWorksCMServerState # Deprecated service
    - CodeStarProject # Deprecated service
    - CodeStarConnection # Deprecated service
    - CodeStarNotification # Deprecated service
    - Cloud9Environment # Deprecated service
    - CloudSearchDomain # Deprecated service
    - RedshiftServerlessSnapshot # Deprecated service
    - RedshiftServerlessNamespace # Deprecated service
    - RedshiftServerlessWorkgroup # Deprecated service
    - ElasticTranscoderPreset # Deprecated service
    - ElasticTranscoderPipeline # Deprecated service
# excluded because property tag is not supported. Not all resources support tags unfortunately.
    - GlueDatabase
    - ResourceExplorer2Index
    - ResourceExplorer2View
    - Macie
    - IAMAccountSettingPasswordPolicy
    # - S3Bucket
    # - DynamoDBTable
    # - DynamoDBTableItem

presets:
  # common:
  #   filters:
  #     BudgetsBudget:
  #       - property: Name
  #         value: "My Zero-Spend Budget"

  organization:
    filters:
      IAMSAMLProvider:
        - property: ARN
          type: contains
          value: "AWSSSO"

      IAMRole:
        - property: Name
          type: contains
          value: "OrganizationAccountAccessRole"
        - property: Name
          type: contains
          value: "AWSReservedSSO"
        - property: Name
          type: contains
          value: "AWSServiceRole"
        - property: Name
          type: regex
          value: "dev-.*"

      IAMRolePolicyAttachment:
        - property: RoleName
          value: "OrganizationAccountAccessRole"
        - property: RoleName
          type: contains
          value: "AWSReservedSSO"
        - property: RoleName
          type: contains
          value: "AWSServiceRole"
        - property: RoleName
          type: regex
          value: "dev-.*"

      IAMPolicy:
        - property: Name
          type: contains
          value: "dev-.*"

  defaults:
    filters:
      EC2Subnet:
        - property: DefaultVPC
          value: "true"
      EC2DefaultSecurityGroupRule:
        - property: DefaultVPC
          value: "true"
      EC2DHCPOption:
        - property: DefaultVPC
          value: "true"
      EC2VPC:
        - property: IsDefault
          value: "true"
      EC2InternetGateway:
        - property: DefaultVPC
          value: "true"
      EC2InternetGatewayAttachment:
        - property: DefaultVPC
          value: "true"

  project:
    filters:
      __global__:
        - property: tag:release-environment
          value: "val-157373"
          invert: "true"
          
accounts:
  "<account_id>":
    presets:
      # - common
      - organization
      - defaults
      - project

```
