### ISSUE TITLE
Guidance on cloud control api resources 

### ISSUE THREAD

**Issue by corybekk** [ekristen/aws-nuke#502]
Hi there,
I see that [config-cloud-control.md](https://github.com/ekristen/aws-nuke/blob/553175e4d87de18e8e9d5cd78b49a14ce479d141/docs/config-cloud-control.md) says "coming soon" and was wondering if the old cloud-control `config.yml` functionality is still supported?

Context: 

In the previous version of `aws-nuke`, we used the `cloud-control` attribute in `config.yml` to handle resources without a corresponding package under `aws-nuke/resources`. However, after migrating our configuration file to use this version of `aws-nuke`, I noticed that Cloud Control API resources are not being picked up.

Here’s a small simplified example:

```
resource-types:
  includes:
    - AccessAnalyzer
    - ACMCertificate
    - APIGatewayAPIKey
  alternatives:
    - AWS::Bedrock::Agent
    - AWS::Bedrock::Flow
```
Could you confirm if this functionality is still supported?
Thanks!
