### ISSUE TITLE
Exclude specific S3 bucket from nuking

### ISSUE THREAD

**Issue by S733** [ekristen/aws-nuke#509]
How to exclude specific S3 Bucket from nuking. I tried the following two types of filtering, but still the bucket was shown as "- would remove" and the scan status shows "0 filtered".

A tag was added to the bucket as Name:example-test-bckt, do we need to provide the tag's key and value or only the value?

```
presets:
  example:
    filters:
      S3Bucket:
        - property: tag:example-test-bckt
          value: "ignore"
      __global__:
         - property: tag:example-test-bckt
           value: "ignore"
```

**Comment by ekristen** [comment]
Please provide configuration and logs.

**Comment by ekristen** [comment]
@S733 please check out the documentation and the quick start configs, you are missing some key components. Also please see https://aws-nuke.ekristen.dev/config-filtering/ for full documentation on filters.

Unfortunately you've got a couple things wrong here.

1. You aren't telling the account to use the preset which means the preset is just defined but never used.
2. You are using the filters incorrectly, filters match on values of properties, that's why it's `property` and `value`.

### Fixing Presets

```yaml
regions:
- us-east-1
blocklist:
- "8xxxxxxxxxx0"
- "5xxxxxxxxxx9"
accounts:
  "50xxxxxxxx30":
    presets:
      - example 
presets:
  example
```

## Fixing Filters

```
us-east-1 - S3Bucket - s3://example-test-bckt - [CreationDate: "2025-01-09T19:25:06Z", Name: "example-test-bckt", ObjectLock: "", tag:Name: "example-test-bckt"] - would remove
```

`s3://example-test-bckt` is the *stringer* it can be matched with a simple `- s3://example-test-bckt` as a filter.

Everything side the `[ ]` are properties.  YOu do not have a tag called `example-test-bckt` you have a tag called `Name` only access via `tag:Name` and you have properties `Name`, `CreationDate` and `ObjectLock`

```yaml
presets:
  example:
    filters:
      S3Bucket:
        - property: tag:Name
          value: "example-test-bckt"
```
