### ISSUE TITLE
Prevent deletion of Amazon MSK network interfaces

### ISSUE THREAD

**Issue by apgrucza** [ekristen/aws-nuke#528]
Amazon MSK automatically creates network interfaces (ENIs) in the customer account, and if these are deleted then you lose the ability to connect to the MSK cluster. There is no way to recreate these ENIs apart from deleting and recreating the cluster.

These ENIs are untagged but have a `Description` property in the format `DO NOT DELETE - Amazon MSK network interface for cluster <cluster_arn>.`. However, `Description` is not available as a property to filter on. If added, then they could be filtered out like this:

```
      EC2NetworkInterface:
        - property: Description
          type: glob
          value: "DO NOT DELETE - *"
```
