### ISSUE TITLE
CloudFront distributions are disabled, but not deleted

### ISSUE THREAD

**Issue by Petersoj** [ekristen/aws-nuke#557]
In `v3.47.1`, `CloudFrontDistributionDeployment` shows up in the resource listing, but `CloudFrontDistribution` does not. This causes `aws-nuke` to disable the CloudFront distributions, but not fully deleted them after being disabled. Because they aren't deleted, other dependent resources like cache policies and response header policies cannot be deleted, causing `aws-nuke` to fail in the end.
Edit: it's also worth noting that my config specifically includes resource types. Snippet:
```yml
resource-types:
  includes:
    - ...
    - CloudFrontCachePolicy
    - CloudFrontDistribution
    - CloudFrontDistributionDeployment
    - CloudFrontFunction
    - CloudFrontKeyGroup
    - CloudFrontOriginAccessControl
    - CloudFrontOriginAccessIdentity
    - CloudFrontOriginRequestPolicy
    - CloudFrontPublicKey
    - CloudFrontResponseHeadersPolicy
    - ...
```
