### ISSUE TITLE
Resources failing to nuke / aws nuke stalls

### ISSUE THREAD

**Issue by BwL1289** [ekristen/aws-nuke#591]
I'm somewhat sure this is user error, but I've been using `aws nuke` for a few months with no issues and started to see the below.

Note: I do not have S3Object enabled and this Cfn Stack does not have deletion protection. Here's the relevant snippet of my config:

```yaml
# MARK: - Disable deletion protection on everything except for CloudFormation stacks
settings:
  EC2Image:
    IncludeDisabled: true
    IncludeDeprecated: true
    DisableDeregistrationProtection: true
  EC2Instance:
    DisableStopProtection: true
    DisableDeletionProtection: true
  RDSInstance:
    DisableDeletionProtection: true
  # Do not delete Cfn stacks with deletion protection enabled
  CloudFormationStack:
    DisableDeletionProtection: false
  DynamoDBTable:
    DisableDeletionProtection: true
  CognitoUserPool:
    DisableDeletionProtection: true
  # Do not include service linked roles in the deletion process
  IAMRole:
    IncludeServiceLinkedRoles: false

# MARK: - Exclude specific resources from being nuked
resource-types:
  excludes:
    # MARK: - Nuke recommended exclusions
    - S3Object # Excluded because S3 bucket removal handles removing all S3Objects
    - ServiceCatalogTagOption # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - ServiceCatalogTagOptionPortfolioAttachment # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - FMSNotificationChannel # Excluded because it's not available
    - FMSPolicy # Excluded because it's not available
    - MachineLearningMLModel # Excluded due to ML being unavailable
    - MachineLearningDataSource # Excluded due to ML being unavailable
    - MachineLearningBranchPrediction # Excluded due to ML being unavailable
    - MachineLearningEvaluation # Excluded due to ML being unavailable
    - RoboMakerDeploymentJob # Deprecated Service
    - RoboMakerFleet # Deprecated Service
    - RoboMakerRobot # Deprecated Service
    - RoboMakerSimulationJob
    - RoboMakerRobotApplication
    - RoboMakerSimulationApplication
    - OpsWorksApp # Deprecated service
    - OpsWorksInstance # Deprecated service
    - OpsWorksLayer # Deprecated service
    - OpsWorksUserProfile # Deprecated service
    - OpsWorksCMBackup # Deprecated service
    - OpsWorksCMServer # Deprecated service
    - OpsWorksCMServerState # Deprecated service
    - CodeStarProject # Deprecated service
    - CodeStarConnection # Deprecated service
    - CodeStarNotification # Deprecated service
    - Cloud9Environment # Deprecated service
    - CloudSearchDomain # Deprecated service
    - RedshiftServerlessSnapshot # Deprecated service
    - RedshiftServerlessNamespace # Deprecated service
    - RedshiftServerlessWorkgroup # Deprecated service
```

1. I nuked an account and got a number of failures (and some successful removals) and then aws nuke stopped. I cancelled after about 15 minutes of it stalling so I could try again (see no. 2 below). Cloudformation originally indicates the reason for the failure is `resource sg-<redacted> has a dependent object`, though aws nuke should just continue trying.

```text
global - IAMInstanceProfile - WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUHeadNodeRoleInstanceProfileSvcEUHeadNodeInstanceProfileFDD0898B-E9DPOouYnugv - [Name: "WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUHeadNodeRoleInstanceProfileSvcEUHeadNodeInstanceProfileFDD0898B-E9DPOouYnugv", Path: "/"] - failed
--
global - IAMInstanceProfile - WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUWorkerNodeRoleInstanceProfileSvcEUWorkerNodeInstanceProfile501E92C1-2XQeIctzX8YU - [Name: "WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUWorkerNodeRoleInstanceProfileSvcEUWorkerNodeInstanceProfile501E92C1-2XQeIctzX8YU", Path: "/"] - failed
global - IAMInstanceProfileRole - WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUHeadNodeRoleInstanceProfileSvcEUHeadNodeInstanceProfileFDD0898B-E9DPOouYnugv -> WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUHeadNodeR-hQhPOj69FqKF - [InstanceProfile: "WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUHeadNodeRoleInstanceProfileSvcEUHeadNodeInstanceProfileFDD0898B-E9DPOouYnugv", InstanceRole: "WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUHeadNodeR-hQhPOj69FqKF", role:CreateDate: "2025-03-10T17:06:19Z", role:LastUsedDate: "2025-03-10 17:06:19 +0000 UTC", role:Path: "/"] - triggered remove
global - IAMInstanceProfileRole - WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUWorkerNodeRoleInstanceProfileSvcEUWorkerNodeInstanceProfile501E92C1-2XQeIctzX8YU -> WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUWorkerNod-q35biPozcgwD - [InstanceProfile: "WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUWorkerNodeRoleInstanceProfileSvcEUWorkerNodeInstanceProfile501E92C1-2XQeIctzX8YU", InstanceRole: "WsStack-WsJupyterHubSvcDataPlaneSvcEUSvcEUWorkerNod-q35biPozcgwD", role:CreateDate: "2025-03-10T17:06:19Z", role:LastUsedDate: "2025-03-10 17:06:19 +0000 UTC", role:Path: "/"] - triggered remove
global - IAMRole - AWSBackupDefaultServiceRole - [CreateDate: "2025-03-10T17:45:31Z", LastUsedDate: "2025-03-10T17:45:31Z", Name: "AWSBackupDefaultServiceRole", Path: "/service-role/"] - failed

... logs continue

<redacted> - EC2NetworkInterface - eni-<redacted> - [AvailabilityZone: "<redacted>a", ID: "eni-<redacted>", PrivateIPAddress: "<redacted>", Status: "in-use", SubnetID: "subnet-<redacted>", VPC: "vpc-<redacted>", tag:aws:ecs:clusterName: "WsStack-WsJupyterHubSvcControlPlaneSvcEcsClusterSvcEcsClusterEcsClusterSvc5D52B935-bzG6mVh7yrr0", tag:username: "<redacted>"] - failed
<redacted> - EC2NetworkInterface - eni-<redacted> - [AvailabilityZone: "<redacted>a", ID: "eni-<redacted>", PrivateIPAddress: "<redacted>", Status: "in-use", SubnetID: "subnet-<redacted>", VPC: "vpc-<redacted>", tag:aws:ecs:clusterName: "WsStack-WsJupyterHubSvcControlPlaneSvcEcsClusterSvcEcsClusterEcsClusterSvc5D52B935-bzG6mVh7yrr0", tag:aws:ecs:serviceName: "WsStack-WsJupyterHubSvcControlPlaneSvcApplicationLoadBalancerFargateSvcAlbFargateSvcServiceBB0B01A5-aGK7tOizpVJT"] - failed
<redacted> - EC2NetworkInterface - eni-<redacted> - [AvailabilityZone: "<redacted>a", ID: "eni-<redacted>", PrivateIPAddress: "<redacted>", Status: "in-use", SubnetID: "subnet-<redacted>", VPC: "vpc-<redacted>"] - failed
<redacted> - EC2NetworkInterface - eni-<redacted> - [AvailabilityZone: "<redacted>a", ID: "eni-<redacted>", PrivateIPAddress: "<redacted>", Status: "in-use", SubnetID: "subnet-<redacted>", VPC: "vpc-<redacted>"] - failed
<redacted> - EC2NetworkInterface - eni-<redacted> - [AvailabilityZone: "<redacted>a", ID: "eni-<redacted>", PrivateIPAddress: "<redacted>", Status: "in-use", SubnetID: "subnet-<redacted>", VPC: "vpc-<redacted>"] - failed
<redacted> - EC2NetworkInterface - eni-<redacted> - [AvailabilityZone: "<redacted>b", ID: "eni-<redacted>", PrivateIPAddress: "<redacted>", Status: "in-use", SubnetID: "subnet-<redacted>", VPC: "vpc-<redacted>"] - failed
<redacted> - EC2NetworkInterface - eni-<redacted> - [AvailabilityZone: "<redacted>b", ID: "eni-<redacted>", PrivateIPAddress: "<redacted>", Status: "in-use", SubnetID: "subnet-<redacted>", VPC: "vpc-<redacted>"] - failed
<redacted> - EC2NetworkInterface - eni-<redacted> - [AvailabilityZone: "<redacted>c", ID: "eni-<redacted>", PrivateIPAddress: "<redacted>", Status: "in-use", SubnetID: "subnet-<redacted>", VPC: "vpc-<redacted>"] - failed
<redacted> - EC2NetworkInterface - eni-<redacted> - [AvailabilityZone: "<redacted>c", ID: "eni-<redacted>", PrivateIPAddress: "<redacted>", Status: "in-use", SubnetID: "subnet-<redacted>", VPC: "vpc-00a4d439c2492cf86", tag:aws:ecs:clusterName: "WsStack-WsJupyterHubSvcControlPlaneSvcEcsClusterSvcEcsClusterEcsClusterSvc5D52B935-bzG6mVh7yrr0", tag:username: "<redacted>"] - failed
<redacted> - EC2NetworkInterface - eni-<redacted> - [AvailabilityZone: "<redacted>c", ID: "eni-<redacted>", PrivateIPAddress: "<redacted>", Status: "in-use", SubnetID: "subnet-<redacted>", VPC: "vpc-<redacted>"] - failed
<redacted> - EC2NetworkInterface - eni-<redacted> - [AvailabilityZone: "<redacted>c", ID: "eni-<redacted>", PrivateIPAddress: "<redacted>", Status: "in-use", SubnetID: "subnet-<redacted>", VPC: "vpc-<redacted>"] - failed
<redacted> - EC2Volume - vol-<redacted> - [CreateTime: "2025-03-10T17:57:58Z", State: "in-use", tag:AmazonECSCreated: "arn:aws:ecs:<redacted>:<redacted>:task/WsStack-WsJupyterHubSvcControlPlaneSvcEcsClusterSvcEcsClusterEcsClusterSvc5D52B935-bzG6mVh7yrr0/1ea1f6c19b42471a90105e4e708c2663", tag:AmazonECSManaged: "true", tag:aws:ecs:clusterName: "WsStack-WsJupyterHubSvcControlPlaneSvcEcsClusterSvcEcsClusterEcsClusterSvc5D52B935-bzG6mVh7yrr0", tag:username: "<redacted>"] - failed
<redacted> - EC2Volume - vol-<redacted> - [CreateTime: "2025-03-10T17:53:31Z", State: "in-use", tag:AmazonECSCreated: "arn:aws:ecs:<redacted>:<redacted>:task/WsStack-WsJupyterHubSvcControlPlaneSvcEcsClusterSvcEcsClusterEcsClusterSvc5D52B935-bzG6mVh7yrr0/b89a9263de3d49fe86e0403220838eac", tag:AmazonECSManaged: "true", tag:aws:ecs:clusterName: "WsStack-WsJupyterHubSvcControlPlaneSvcEcsClusterSvcEcsClusterEcsClusterSvc5D52B935-bzG6mVh7yrr0", tag:username: "<redacted>"] - failed
<redacted> - AWSBackupRecoveryPoint - arn:aws:backup:<redacted>:<redacted>:recovery-point:18e47a81-0ec3-426b-b944-d920d4a33f25 - [BackupVault: "yterHubSvcDataPlaneSvcEfsSvcEfsBackupVaultDD60626C"] - triggered remove

... logs continue

<redacted> - ECSTaskDefinition - arn:aws:ecs:<redacted>:<redacted>:task-definition/WsStackWsWatcherSvcTaskDefSvcTaskDefSvcFargateTaskDefCD726A6B:10 - triggered remove
<redacted> - ECSTaskDefinition - arn:aws:ecs:<redacted>:<redacted>:task-definition/jupyterhub-lab-task-definition-family-workspace-<redacted>F1EA92B2:18 - triggered remove

... logs stop
```

2. I then tried again and left it running for a few hours. It stalls right after it starts nuking and about 2 hours in indicates that the security token has expired and the rest of the failures start rolling in

```text
no-prompt flag set, continuing without prompting user
waiting 3s before continuing
global - IAMRole - AWSBackupDefaultServiceRole - [CreateDate: "2025-03-10T17:45:31Z", LastUsedDate: "2025-03-10T17:45:51Z", Name: "AWSBackupDefaultServiceRole", Path: "/service-role/"] - triggered remove
global - IAMRole - WsStack-CustomVpcRestrictDefaultSGCustomResourcePro-sHfwtMcFoWCx - [CreateDate: "2025-03-10T17:05:38Z", LastUsedDate: "2025-03-10T17:06:24Z", Name: "WsStack-CustomVpcRestrictDefaultSGCustomResourcePro-sHfwtMcFoWCx", Path: "/", tag:AppManagerCFNStackKey: "WsStack"] - triggered remove
global - IAMRole - WsStack-WsNetworkSvcVpcSvcVpcSvcVpcVpcSvcNetworkFlo-P4fjWoeCiUkq - [CreateDate: "2025-03-10T17:05:24Z", LastUsedDate: "2025-03-10T20:34:54Z", Name: "WsStack-WsNetworkSvcVpcSvcVpcSvcVpcVpcSvcNetworkFlo-P4fjWoeCiUkq", Path: "/", tag:AppManagerCFNStackKey: "WsStack", tag:Name: "WsStack/WsNetworkSvc/VpcSvc/VpcSvcVpc/VpcSvcNetworkFlowLog", tag:service-name: "workspace-network-svc"] - triggered remove
<redacted> - AWSBackupVaultAccessPolicy - aws/efs/automatic-backup-vault - [] - triggered remove
INFO[2025-03-10T16:04:13-05:00]cloudformation-stack.go:271 CloudFormationStack stackName=WsStack delete failed. Attempting to retain and delete stack  component=scanner region=<redacted> resource=ECSTaskDefinition
ERRO[2025-03-10T16:22:08-05:00]cloudformation-stack.go:172 CloudFormationStack stackName=WsStack attempt=0 maxAttempts=3 delete failed: ResourceNotReady: failed waiting for successful resource state  component=scanner region=<redacted> resource=ECSTaskDefinition
INFO[2025-03-10T16:22:08-05:00]cloudformation-stack.go:271 CloudFormationStack stackName=WsStack delete failed. Attempting to retain and delete stack  component=scanner region=<redacted> resource=ECSTaskDefinition
ERRO[2025-03-10T18:33:49-05:00]cloudformation-stack.go:172 CloudFormationStack stackName=WsStack attempt=1 maxAttempts=3 delete failed: ResourceNotReady: exceeded wait attempts  component=scanner region=<redacted> resource=ECSTaskDefinition
ERRO[2025-03-10T18:33:50-05:00]cloudformation-stack.go:172 CloudFormationStack stackName=WsStack attempt=2 maxAttempts=3 delete failed: ExpiredToken: The security token included in the request is expired
        status code: 403, request id: 028779bf-dad9-4fab-9497-0e1dc18d182e  component=scanner region=<redacted> resource=ECSTaskDefinition
ERRO[2025-03-10T18:33:50-05:00]cloudformation-stack.go:172 CloudFormationStack stackName=WsStack attempt=3 maxAttempts=3 delete failed: ExpiredToken: The security token included in the request is expired
        status code: 403, request id: 431cbcfa-8e7a-4fef-8ae7-3d77d5b54dfc  component=scanner region=<redacted> resource=ECSTaskDefinition
<redacted> - CloudFormationStack - WsStack - [CreationTime: "2025-03-10T17:05:00Z", LastUpdatedTime: "2025-03-10T17:05:17Z", Name: "WsStack", Status: "DELETE_FAILED", tag:AppManagerCFNStackKey: "WsStack"] - failed
<redacted> - EC2VPC - vpc-00a4d439c2492cf86 - [ID: "vpc-00a4d439c2492cf86", IsDefault: "false", OwnerID: "<redacted>", tag:AppManagerCFNStackKey: "WsStack", tag:Name: "WsStack/WsNetworkSvc/VpcSvc/VpcSvcVpc", tag:aws:cloudformation:logical-id: "WsNetworkSvcVpcSvcVpcSvcVpc0A0216C4", tag:aws:cloudformation:stack-id: "arn:aws:cloudformation:<redacted>:<redacted>:stack/WsStack/cd21a0a0-fdd1-11ef-88ea-0e2d40da4d73", tag:aws:cloudformation:stack-name: "WsStack", tag:service-name: "workspace-network-svc"] - failed
<redacted> - EC2InternetGatewayAttachment - igw-02ab7611aa59e8d3e -> vpc-00a4d439c2492cf86 - [DefaultVPC: "false", igw:OwnerID: "<redacted>", tag:igw:AppManagerCFNStackKey: "WsStack", tag:igw:Name: "WsStack/WsNetworkSvc/VpcSvc/VpcSvcVpc", tag:igw:aws:cloudformation:logical-id: "WsNetworkSvcVpcSvcVpcSvcVpcIGW6CD4ECF7", tag:igw:aws:cloudformation:stack-id: "arn:aws:cloudformation:<redacted>:<redacted>:stack/WsStack/cd21a0a0-fdd1-11ef-88ea-0e2d40da4d73", tag:igw:aws:cloudformation:stack-name: "WsStack", tag:igw:service-name: "workspace-network-svc", tag:vpc:AppManagerCFNStackKey: "WsStack", tag:vpc:Name: "WsStack/WsNetworkSvc/VpcSvc/VpcSvcVpc", tag:vpc:aws:cloudformation:logical-id: "WsNetworkSvcVpcSvcVpcSvcVpc0A0216C4", tag:vpc:aws:cloudformation:stack-id: "arn:aws:cloudformation:<redacted>:<redacted>:stack/WsStack/cd21a0a0-fdd1-11ef-88ea-0e2d40da4d73", tag:vpc:aws:cloudformation:stack-name: "WsStack", tag:vpc:service-name: "workspace-network-svc", vpc:OwnerID: "<redacted>"] - failed

... more logs

global - IAMRole - AWSBackupDefaultServiceRole - [CreateDate: "2025-03-10T17:45:31Z", LastUsedDate: "2025-03-10T17:45:51Z", Name: "AWSBackupDefaultServiceRole", Path: "/service-role/"] - triggered remove
global - IAMRole - WsStack-CustomVpcRestrictDefaultSGCustomResourcePro-sHfwtMcFoWCx - [CreateDate: "2025-03-10T17:05:38Z", LastUsedDate: "2025-03-10T17:06:24Z", Name: "WsStack-CustomVpcRestrictDefaultSGCustomResourcePro-sHfwtMcFoWCx", Path: "/", tag:AppManagerCFNStackKey: "WsStack"] - triggered remove
global - IAMRole - WsStack-WsNetworkSvcVpcSvcVpcSvcVpcVpcSvcNetworkFlo-P4fjWoeCiUkq - [CreateDate: "2025-03-10T17:05:24Z", LastUsedDate: "2025-03-10T20:34:54Z", Name: "WsStack-WsNetworkSvcVpcSvcVpcSvcVpcVpcSvcNetworkFlo-P4fjWoeCiUkq", Path: "/", tag:AppManagerCFNStackKey: "WsStack", tag:Name: "WsStack/WsNetworkSvc/VpcSvc/VpcSvcVpc/VpcSvcNetworkFlowLog", tag:service-name: "workspace-network-svc"] - triggered remove
<redacted> - AWSBackupVaultAccessPolicy - aws/efs/automatic-backup-vault - [] - triggered remove
INFO[2025-03-10T16:04:13-05:00]cloudformation-stack.go:271 CloudFormationStack stackName=WsStack delete failed. Attempting to retain and delete stack  component=scanner region=<redacted> resource=ECSTaskDefinition
ERRO[2025-03-10T16:22:08-05:00]cloudformation-stack.go:172 CloudFormationStack stackName=WsStack attempt=0 maxAttempts=3 delete failed: ResourceNotReady: failed waiting for successful resource state  component=scanner region=<redacted> resource=ECSTaskDefinition
INFO[2025-03-10T16:22:08-05:00]cloudformation-stack.go:271 CloudFormationStack stackName=WsStack delete failed. Attempting to retain and delete stack  component=scanner region=<redacted> resource=ECSTaskDefinition
ERRO[2025-03-10T18:33:49-05:00]cloudformation-stack.go:172 CloudFormationStack stackName=WsStack attempt=1 maxAttempts=3 delete failed: ResourceNotReady: exceeded wait attempts  component=scanner region=<redacted> resource=ECSTaskDefinition
ERRO[2025-03-10T18:33:50-05:00]cloudformation-stack.go:172 CloudFormationStack stackName=WsStack attempt=2 maxAttempts=3 delete failed: ExpiredToken: The security token included in the request is expired
        status code: 403, request id: 028779bf-dad9-4fab-9497-0e1dc18d182e  component=scanner region=<redacted> resource=ECSTaskDefinition
ERRO[2025-03-10T18:33:50-05:00]cloudformation-stack.go:172 CloudFormationStack stackName=WsStack attempt=3 maxAttempts=3 delete failed: ExpiredToken: The security token included in the request is expired
        status code: 403, request id: 431cbcfa-8e7a-4fef-8ae7-3d77d5b54dfc  component=scanner region=<redacted> resource=ECSTaskDefinition
<redacted> - CloudFormationStack - WsStack - [CreationTime: "2025-03-10T17:05:00Z", LastUpdatedTime: "2025-03-10T17:05:17Z", Name: "WsStack", Status: "DELETE_FAILED", tag:AppManagerCFNStackKey: "WsStack"] - failed
<redacted> - EC2VPC - vpc-00a4d439c2492cf86 - [ID: "vpc-00a4d439c2492cf86", IsDefault: "false", OwnerID: "<redacted", tag:AppManagerCFNStackKey: "WsStack", tag:Name: "WsStack/WsNetworkSvc/VpcSvc/VpcSvcVpc", tag:aws:cloudformation:logical-id: "WsNetworkSvcVpcSvcVpcSvcVpc0A0216C4", tag:aws:cloudformation:stack-id: "arn:aws:cloudformation:<redacted>:<redacted:stack/WsStack/cd21a0a0-fdd1-11ef-88ea-0e2d40da4d73", tag:aws:cloudformation:stack-name: "WsStack", tag:service-name: "workspace-network-svc"] - failed
<redacted> - EC2InternetGatewayAttachment - igw-02ab7611aa59e8d3e -> vpc-00a4d439c2492cf86 - [DefaultVPC: "false", igw:OwnerID: "<redacted", tag:igw:AppManagerCFNStackKey: "WsStack", tag:igw:Name: "WsStack/WsNetworkSvc/VpcSvc/VpcSvcVpc", tag:igw:aws:cloudformation:logical-id: "WsNetworkSvcVpcSvcVpcSvcVpcIGW6CD4ECF7", tag:igw:aws:cloudformation:stack-id: "arn:aws:cloudformation:<redacted>:<redacted:stack/WsStack/cd21a0a0-fdd1-11ef-88ea-0e2d40da4d73", tag:igw:aws:cloudformation:stack-name: "WsStack", tag:igw:service-name: "workspace-network-svc", tag:vpc:AppManagerCFNStackKey: "WsStack", tag:vpc:Name: "WsStack/WsNetworkSvc/VpcSvc/VpcSvcVpc", tag:vpc:aws:cloudformation:logical-id: "WsNetworkSvcVpcSvcVpcSvcVpc0A0216C4", tag:vpc:aws:cloudformation:stack-id: "arn:aws:cloudformation:<redacted>:<redacted:stack/WsStack/cd21a0a0-fdd1-11ef-88ea-0e2d40da4d73", tag:vpc:aws:cloudformation:stack-name: "WsStack", tag:vpc:service-name: "workspace-network-svc", vpc:OwnerID: "<redacted"] - failed
<redacted> - EC2SecurityGroup - sg-<redacted> - [ID: "sg-<redacted>", Name: "WsStack-WsJupyterHubSvcDataPlaneSvcHubSvcExportEfsDataToS3SvcExportEfsDataLambdaSvcSecurityGroup255670F3-89J1fjqwh5xT", OwnerID: "<redacted", tag:AppManagerCFNStackKey: "WsStack", tag:aws:cloudformation:logical-id: "WsJupyterHubSvcDataPlaneSvcHubSvcExportEfsDataToS3SvcExportEfsDataLambdaSvcSecurityGroup255670F3", tag:aws:cloudformation:stack-id: "arn:aws:cloudformation:<redacted>:<redacted:stack/WsStack/cd21a0a0-fdd1-11ef-88ea-0e2d40da4d73", tag:aws:cloudformation:stack-name: "WsStack", tag:service-name: "jupyterhub-export-efs-data-lambda-func-svc"] - failed
<redacted> - EC2SecurityGroup - sg-<redacted> - [ID: "sg-<redacted>", Name: "WsStack-WsJupyterHubSvcDataPlaneSvcHubSvcHubTaskDefContainerSvcSecurityGroup813120F7-spFW3QGaqfrT", OwnerID: "<redacted", tag:AppManagerCFNStackKey: "WsStack", tag:aws:cloudformation:logical-id: "WsJupyterHubSvcDataPlaneSvcHubSvcHubTaskDefContainerSvcSecurityGroup813120F7", tag:aws:cloudformation:stack-id: "arn:aws:cloudformation:<redacted>:<redacted:stack/WsStack/cd21a0a0-fdd1-11ef-88ea-0e2d40da4d73", tag:aws:cloudformation:stack-name: "WsStack", tag:service-name: "jupyterhub-hub-ecs-task-def-container-svc"] - failed

Removal requested: 0 waiting, 82 failed, 3108 skipped, 0 finished

... more logs

<redacted> - CloudWatchLogsLogGroup - WsStack-WsNetworkSvcVpcSvcVpcSvcVpcVpcSvcNetworkFlowLogLogGroup406657F3-ysZQEVihv8BH - [CreatedTime: "1741304127720", CreationTime: "2025-03-06T23:35:27Z", LastEvent: "2025-03-06T22:21:49-06:00", Name: "WsStack-WsNetworkSvcVpcSvcVpcSvcVpcVpcSvcNetworkFlowLogLogGroup406657F3-ysZQEVihv8BH", RetentionInDays: "731", logGroupName: "WsStack-WsNetworkSvcVpcSvcVpcSvcVpcVpcSvcNetworkFlowLogLogGroup406657F3-ysZQEVihv8BH", tag:AppManagerCFNStackKey: "WsStack", tag:Name: "WsStack/WsNetworkSvc/VpcSvc/VpcSvcVpc/VpcSvcNetworkFlowLog", tag:aws:cloudformation:logical-id: "WsNetworkSvcVpcSvcVpcSvcVpcVpcSvcNetworkFlowLogLogGroup406657F3", tag:aws:cloudformation:stack-id: "arn:aws:cloudformation:<redacted>:<redacted>:stack/WsStack/9cd85c40-fae3-11ef-b96c-0e321035bced", tag:aws:cloudformation:stack-name: "WsStack", tag:service-name: "workspace-network-svc"] - failed
ExpiredTokenException: The security token included in the request is expired
        status code: 400, request id: 3fbad10b-2ea5-47f4-a6a3-a82140f3a2ce
<redacted> - CloudWatchLogsLogGroup - jupyterhub-lab-task-definition-container-workspace-<redacted>04437C31 - [CreatedTime: "1741408008889", CreationTime: "2025-03-08T04:26:48Z", LastEvent: "2025-03-10T12:59:03-05:00", Name: "jupyterhub-lab-task-definition-container-workspace-<redacted>04437C31", logGroupName: "jupyterhub-lab-task-definition-container-workspace-<redacted>04437C31"] - failed
ExpiredTokenException: The security token included in the request is expired
        status code: 400, request id: 39a82553-b8fe-471b-b9a4-97a4042bca01
FATA[2025-03-10T18:42:55-05:00]main.go:51 failed
```

Cloudformation then indicates`Resource handler returned message: "The subnet 'subnet-<redacted>' has dependencies and cannot be deleted.`

Is there something obvious I'm missing?
