### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by kurtmc** [ekristen/aws-nuke#597]
I am getting `fatal error: all goroutines are asleep - deadlock!` on version v3.48.2

Here is the whole stack trace:

```
goroutine 1 [select, 2 minutes]:

golang.org/x/sync/semaphore.(*Weighted).Acquire(0xc0001680f0, {0x8c92e38, 0xc00043a280}, 0x1)

	golang.org/x/sync@v0.11.0/semaphore/semaphore.go:74 +0x339

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run(0xc000b947e0, {0x8c92e38, 0xc00043a280})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:87 +0xc5

github.com/ekristen/libnuke/pkg/nuke.(*Nuke).runScanner(0xc0008e2140, {0x8c92e38?, 0xc00043a280?}, 0xc000b947e0, 0xc000990618)

	github.com/ekristen/libnuke@v0.24.3/pkg/nuke/nuke.go:384 +0x45

github.com/ekristen/libnuke/pkg/nuke.(*Nuke).Scan(0xc0008e2140, {0x8c92e38, 0xc00043a280})

	github.com/ekristen/libnuke@v0.24.3/pkg/nuke/nuke.go:428 +0x1c5

github.com/ekristen/libnuke/pkg/nuke.(*Nuke).Run(0xc0008e2140, {0x8c92e38, 0xc00043a280})

	github.com/ekristen/libnuke@v0.24.3/pkg/nuke/nuke.go:207 +0x1ae

github.com/ekristen/aws-nuke/v3/pkg/commands/nuke.execute(0xc0001eef00)

	github.com/ekristen/aws-nuke/v3/pkg/commands/nuke/nuke.go:238 +0x2305

github.com/urfave/cli/v2.(*Command).Run(0xc000492580, 0xc0001eef00, {0xc00042da70, 0x9, 0x9})

	github.com/urfave/cli/v2@v2.27.5/command.go:276 +0x7be

github.com/urfave/cli/v2.(*Command).Run(0xc000492b00, 0xc0001eedc0, {0xc0000703c0, 0xa, 0xa})

	github.com/urfave/cli/v2@v2.27.5/command.go:269 +0xa45

github.com/urfave/cli/v2.(*App).RunContext(0xc000518200, {0x8c92b60, 0xd4fb620}, {0xc0000703c0, 0xa, 0xa})

	github.com/urfave/cli/v2@v2.27.5/app.go:333 +0x5a5

github.com/urfave/cli/v2.(*App).Run(...)

	github.com/urfave/cli/v2@v2.27.5/app.go:307

main.main()

	github.com/ekristen/aws-nuke/v3/main.go:50 +0x1e9


goroutine 5577 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82deeea, 0xf}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 3908 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82deebd, 0xf}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 5529 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82f94ff, 0x13}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 5503 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82cdf45, 0xb}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 5278 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x8311782, 0x16}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 5316 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82f9609, 0x13}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 5547 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82cde1c, 0xb}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 2939 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82c5645, 0x8}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 5739 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82d131d, 0xc}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 6129 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82e4a6d, 0x10}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 5419 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82d99ab, 0xe}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 3397 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82c565d, 0x8}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 5652 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x833a5db, 0x1b}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 5764 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82f9642, 0x13}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 5702 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82cdee2, 0xb}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b


goroutine 5910 [chan send, 2 minutes]:

github.com/ekristen/libnuke/pkg/scanner.(*Scanner).list(0xc000b947e0, {0x8c92e38?, 0xc00043a280?}, {0xc0005aff40, 0xe}, {0x82d9a0d, 0xe}, {0x6246a80, 0xc00087ea20})

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:173 +0xa16

created by github.com/ekristen/libnuke/pkg/scanner.(*Scanner).Run in goroutine 1

	github.com/ekristen/libnuke@v0.24.3/pkg/scanner/scanner.go:96 +0x6b
```

I can share the debug logs with you if you need that, but I will need to make sure it's not leaking any of my account information before I do that.

**Comment by ekristen** [comment]
Yeah I'll need debug logs I think to see what it was doing last. I would also like your config.

**Comment by kurtmc** [comment]
config:
```
---
regions:
  - global
  - ap-southeast-2

blocklist:
  - aaaaaaaaaaaa
  - bbbbbbbbbbbb
  - cccccccccccc
  - dddddddddddd
  - eeeeeeeeeeee
  - ffffffffffff
  - gggggggggggg

accounts:
  123456789012:
    filters:
      ACMCertificate:
        - arn:aws:acm:us-east-1:123456789012:certificate/175981bb-05a2-4cb7-bb5d-353098f88bc6
      APIGatewayAPIKey:
        - abcdefg
      APIGatewayRestAPI:
        - asfasda
      APIGatewayUsagePlan:
        - asfas
      CloudFormationStack:
        - aaaaaaaaaaaaaaaaaaaaaa
        - bbbb
        - ccc
        - ddddddddddddddd
      CloudFrontDistribution:
        - KLJLKJKLJLKL
      CloudFrontDistributionDeployment:
        - KLJLKJKLJLKL
      CloudWatchLogsLogGroup:
        - /aws/lambda/aaaaaaaaaa
        - /aws/lambda/bbbbbbbbbbbbbbbbb
      DynamoDBTable:
        - asdfasdfasdfas
      IAMPolicy:
        - arn:aws:iam::123456789012:policy/aaaaaaaaaaaaaaaaaaaaaaaa
        - arn:aws:iam::123456789012:policy/bbbbbbbbbbbbbbbbbbbbbbbbbb
        - arn:aws:iam::123456789012:policy/cccccccccccccccccccccccccccccccccccccccccccc
        - arn:aws:iam::123456789012:policy/dddddddddddd
        - arn:aws:iam::123456789012:policy/service-role/asfdasdfas
      IAMRole:
        - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        - bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
      IAMRolePolicy:
        - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -> bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        - ccccccccccccccccccccccccccccc -> ddddddddddddddddddd
      IAMRolePolicyAttachment:
        - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -> bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        - cccccccccccccccccccccccc -> ddddddddddddddddddddddddddd
      IAMUser:
        - aaaaaaaaaaaa
        - bbbbbbbbbbbbb
      IAMUserAccessKey:
        - type: glob
          value: "aaaaaaaaaaaa -> *"
        - bbbbbbbbbbbbb -> KLKJKLJLK
      IAMUserPolicy:
        - asfasdfasdfas -> asfasdfasdfaswatch-readonly
      IAMUserPolicyAttachment:
        - asfdasdfasdfasdf -> AdministratorAccess
        - asfdasdfasdfasdf -> asfdasdfasdfasdf
      LambdaFunction:
        - aasfdasfd-aasfdasfd
        - aasfdasfd-setup
        - aasfdasfd-source-to-s3
      Route53HostedZone:
        - /hostedzone/KJKLJLKJLKJLKJL (aaaaaaaa.example.com.)
      Route53ResourceRecordSet:
        - _aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aasfdasfd.aaaaaaaa.example.com.
        - aasfdasfd.aaaaaaaa.example.com.
      S3Bucket:
        - s3://aasfdasfd-ap-southeast-2-123456789012
        - s3://aasfdasfd-stack-template20191202013610013800000001
        - s3://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      S3Object:
        - s3://aasfdasfd-ap-southeast-2-123456789012/aasfdasfd_lambda.zip
        - s3://aasfdasfd-ap-southeast-2-123456789012/setup_lambda.zip
        - s3://aasfdasfd-stack-template20191202013610013800000001/route53-aasfdasfd.yml
      SNSSubscription:
        - type: glob
          value: "Owner: 123456789012 ARN: arn:aws:sns:ap-southeast-2:123456789012:aaaaaaaaaaaaaaaaa:*"
        - type: glob
          value: "Owner: 123456789012 ARN: arn:aws:sns:ap-southeast-2:123456789012:bbbbbbbbbbbbbb:*"
      SNSTopic:
        - "TopicARN: arn:aws:sns:ap-southeast-2:123456789012:aaaaaaaaaaaaaaaaa"
        - "TopicARN: arn:aws:sns:ap-southeast-2:123456789012:bbbbbbbbbbbbbb"
      SecretsManagerSecret:
        - type: glob
          value: "arn:aws:secretsmanager:ap-southeast-2:123456789012:secret:asfdasdfas/*"
        - type: glob
          value: "arn:aws:secretsmanager:ap-southeast-2:123456789012:secret:aaaaaa/asfdasdfasdfasdf/aaaaaaaaaaa*"
        - type: glob
          value: "arn:aws:secretsmanager:ap-southeast-2:123456789012:secret:aaaa/aaaaaaaaa*"

    resource-types:
      excludes:
        - DynamoDBTableItem
        - ResourceExplorer2Index
 ```
