### ISSUE TITLE
Bypass alias check does not work

### ISSUE THREAD

**Issue by thesn10** [ekristen/aws-nuke#636]
Bypass alias check does not work. 
I am using the `--no-alias-check` parameter and i specified all accounts in `bypass-alias-check-accounts`.
I have 15+ accounts that i want to nuke and I still get prompted for **every single** alias, which gets really really REALLY TEDIOUS!
I'm thankful for every help!

<img width="771" alt="Image" src="https://github.com/user-attachments/assets/f794b0d4-39e1-4570-8675-78d244e6a531" />

```yaml
regions:
  - eu-central-1
  - eu-north-1

blocklist:
  - 924269703624 # mnt
  - 654654474164 # aws ods test umgebung
  - 992382715689 # cs

bypass-alias-check-accounts:
  - 156041425117
  - 688567271842
  - 881490091235
  - 122610499433
  - 954976331803
  - 147997120223
  - 536697233224
  - 904233092973
  - 242201300246
  - 442042531654
  - 605134464801
  - 225989329782
  - 205930642439
  - 201486033013
  - 536275850854
  - 145018132124

accounts:
  590183933691: #sy
    presets:
      - common
  156041425117: #1
    presets:
      - common
  688567271842: #2
    presets:
      - common
  881490091235: #3
    presets:
      - common
  122610499433: #4
    presets:
      - common
  954976331803: #5
    presets:
      - common
  147997120223: #6
    presets:
      - common
  536697233224: #7
    presets:
      - common
  904233092973: #8
    presets:
      - common
  242201300246: #9
    presets:
      - common
  442042531654: #10
    presets:
      - common
  605134464801: #11
    presets:
      - common
  225989329782: #12
    presets:
      - common
  205930642439: #13
    presets:
      - common
  201486033013: #14
    presets:
      - common
  536275850854: #15
    presets:
      - common
  145018132124: #16
    presets:
      - common


presets:
  common:
    filters:
      IAMRole:
      - "OrganizationAccountAccessRole"
      IAMRolePolicyAttachment:
      - "OrganizationAccountAccessRole -> AdministratorAccess"
      - type: glob
        value: "AWSReservedSSO_CCAdministratorAccess_*"
      - type: glob
        value: "AWSReservedSSO_PowerUserAccess_*"
      EC2Subnet:
        - property: DefaultVPC
          value: "true"
      EC2DefaultSecurityGroupRule:
        - property: DefaultVPC
          value: "true"
      EC2DHCPOption:
        - property: DefaultVPC
          value: "true"
      EC2VPC:
        - property: IsDefault
          value: "true"
      EC2InternetGateway:
        - property: DefaultVPC
          value: "true"
      EC2InternetGatewayAttachment:
        - property: DefaultVPC
          value: "true"

resource-types:
  excludes:
    - IAMSAMLProvider
    - S3Object # Excluded because S3 bucket removal handles removing all S3Objects
    - ServiceCatalogTagOption # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - ServiceCatalogTagOptionPortfolioAttachment # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - FMSNotificationChannel # Excluded because it's not available
    - FMSPolicy # Excluded because it's not available
    - MachineLearningMLModel # Excluded due to ML being unavailable
    - MachineLearningDataSource # Excluded due to ML being unavailable
    - MachineLearningBranchPrediction # Excluded due to ML being unavailable
    - MachineLearningEvaluation # Excluded due to ML being unavailable
    - RoboMakerDeploymentJob # Deprecated Service
    - RoboMakerFleet # Deprecated Service
    - RoboMakerRobot # Deprecated Service
    - RoboMakerSimulationJob
    - RoboMakerRobotApplication
    - RoboMakerSimulationApplication
    - OpsWorksApp # Deprecated service
    - OpsWorksInstance # Deprecated service
    - OpsWorksLayer # Deprecated service
    - OpsWorksUserProfile # Deprecated service
    - OpsWorksCMBackup # Deprecated service
    - OpsWorksCMServer # Deprecated service
    - OpsWorksCMServerState # Deprecated service
    - CodeStarProject # Deprecated service
    - CodeStarConnection # Deprecated service
    - CodeStarNotification # Deprecated service
    - Cloud9Environment # Deprecated service
    - CloudSearchDomain # Deprecated service
    - RedshiftServerlessSnapshot # Deprecated service
    - RedshiftServerlessNamespace # Deprecated service
    - RedshiftServerlessWorkgroup # Deprecated service

settings:
  EC2Image:
    IncludeDisabled: true
    IncludeDeprecated: true
    DisableDeregistrationProtection: true
  EC2Instance:
    DisableStopProtection: true
    DisableDeletionProtection: true
  RDSInstance:
    DisableDeletionProtection: true
    StartClusterToDelete: true
  CloudFormationStack:
    DisableDeletionProtection: true
  DynamoDBTable:
    DisableDeletionProtection: true

```
