### ISSUE TITLE
Invert filter unable to select multiple resources

### ISSUE THREAD

**Issue by Dipesh-Budhiraja** [ekristen/aws-nuke#652]
Hi, I am trying to select multiple instances by their identifiers using invert filter. 
The filter works perfectly if i define a single identifier. But as soon as multiple identifiers for the same resource type are added, then all the instances gets excluded. Can someone please let me know how can i target multiple resources through identifiers like resource names through nuke?

Attaching the configurations for the mentioned scenarios.

Working configuration with a single target:

```
regions:
  - us-west-2

accounts:
  xxxxxxxxxxx:
    filters:
      EC2Instance:
        - property: Identifier
          value: "i-1"
          invert: true

    resource-types:
      includes:
        - EC2Instance


```
Output:

```
starting scan for resources
us-west-2 - EC2Instance - i-1 - [Identifier: "i-1"] - would remove
us-west-2 - EC2Instance - i-2 - [Identifier: "i-2"] - filtered: filtered by config
```

Non working configuration with 2 targets:
```
regions:
  - us-west-2

accounts:
  xxxxxxxxxxx:
    filters:
      EC2Instance:
        - property: Identifier
          value: "i-1"
          invert: true
        - property: Identifier
          value: "i-2"
          invert: true

    resource-types:
      includes:
        - EC2Instance
```

Output:

```
starting scan for resources
us-west-2 - EC2Instance - i-1 - [Identifier: "i-1"] - filtered: filtered by config
us-west-2 - EC2Instance - i-2 - [Identifier: "i-2"] - filtered: filtered by config
```
