### ISSUE TITLE
FATA[0001] no blocklist defined

### ISSUE THREAD

**Issue by Jonathansoufer** [ekristen/aws-nuke#654]
config.yaml content

```
blocklist:
  - 999999999999

blocklist-terms:
  - 'live'

no-blocklist-terms-default: true

regions:
  - all

accounts:
  199455609148:
    filters:
      IAMUser:
        - 'admin'
      IAMUserPolicyAttachment:
        - 'admin -> AdministratorAccess'
      IAMUserAccessKey:
        - 'admin -> XXXXXXXXXXXX'

resource-types:
  includes:
    - IAMUser
    - IAMUserPolicyAttachment
    - IAMUserAccessKey

settings:
  EC2Instance:
    DisableDeletionProtection: true
  RDSInstance:
    DisableDeletionProtection: true

```

run command: `aws-nuke run --config config.yml --profile default`

throws error bellow.

aws-nuke - v3.51.1 - e99cdf9ca2e1570a4083d46aa9b7ebe730e10ee5
FATA[0001] no blocklist defined
