### ISSUE TITLE
SAMLProvider issue

### ISSUE THREAD

**Issue by SSHalome** [ekristen/aws-nuke#680]
Hello, I have this in config:

```
presets:
  sso:
    filters:
      IAMRole:
      - type: "glob"
        value: "AWSReservedSSO_*"
      IAMRolePolicyAttachment:
      - type: "glob"
        value: "AWSReservedSSO_* -> *"
      IAMSAMLProvider:
      - type: "glob"
        value: "*"
```

but it still says that saml would be removed: global - IAMSAMLProvider - arn:aws:iam::1111:saml-provider/AWSSSO_something [ARN: "arn:aws:iam::111:saml-provider/AWSSSO_something", CreateDate: "2023-05-03T12:46:45Z"] - would remove
