### ISSUE TITLE
FATA[0001] specified account doesn't have an alias. For safety reasons you need to specify an account alias. Your production account should contain the term 'prod'

### ISSUE THREAD

**Issue by kopyl** [ekristen/aws-nuke#697]
Here is my config file:

```yaml
regions:
  - global
  - us-east-1
  - eu-west-1

blocklist:
  - "000000000000"

blocklist-terms:
  - "production"
  - "live"

no-blocklist-terms-default: true

account-aliases:
  "***": "my-prod-account"


accounts:
  "***":
    account-alias: "my-prod-account"
    filters:
      IAMUser:
        - "admin"
        - "aws-nuke"
      S3Bucket:
        - "my-logs"
```

All i want is to delete ALL resources on ALL accounts.
